name: Deply to Salesforce Dev Org
on:
  push:
  branches:
   -main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: Set up Salesforce CLI
       uses: amtrack/sfdx-action@v1

     - name: Authenticate to Salesforce
       run: sfdx auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID}} --jwtkeyfile assets/server.key --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername --instanceurl https://login.salesforce.com

     - name: Deploy source to org
       run: sfdx force:source:deploy -p force-app -u ${{secrets.SF_USERNAME}} --checkonly
       